--------------------------------------------------------
--  File created - Tuesday-December-17-2024   
--------------------------------------------------------
DROP TABLE "PERPUSTAKAAN_BCHUB"."ADMIN" cascade constraints;
DROP TABLE "PERPUSTAKAAN_BCHUB"."ANGGOTA" cascade constraints;
DROP TABLE "PERPUSTAKAAN_BCHUB"."BUKU" cascade constraints;
DROP TABLE "PERPUSTAKAAN_BCHUB"."PEMINJAMAN" cascade constraints;
DROP TABLE "PERPUSTAKAAN_BCHUB"."ANGGOTA" cascade constraints;
DROP TABLE "PERPUSTAKAAN_BCHUB"."BUKU" cascade constraints;
DROP TABLE "PERPUSTAKAAN_BCHUB"."PEMINJAMAN" cascade constraints;
DROP PROCEDURE "PERPUSTAKAAN_BCHUB"."AMBIL_SEMUA_PEMINJAMAN";
DROP PROCEDURE "PERPUSTAKAAN_BCHUB"."DELETE_DATA_ANGGOTA";
DROP PROCEDURE "PERPUSTAKAAN_BCHUB"."DELETE_DATA_BUKU";
DROP PROCEDURE "PERPUSTAKAAN_BCHUB"."INSERT_AND_DISPLAY_PEMINJAMAN";
DROP PROCEDURE "PERPUSTAKAAN_BCHUB"."INSERT_DATA_ANGGOTA";
DROP PROCEDURE "PERPUSTAKAAN_BCHUB"."INSERT_DATA_BUKU";
DROP PROCEDURE "PERPUSTAKAAN_BCHUB"."UPDATE_DATA_ANGGOTA";
DROP PROCEDURE "PERPUSTAKAAN_BCHUB"."UPDATE_DATA_BUKU";
DROP SYNONYM "PUBLIC"."DBMS_OUTPUT";
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "PERPUSTAKAAN_BCHUB"."ADMIN" 
   (	"ID_ADMIN" NUMBER(6,0), 
	"NAMA" VARCHAR2(20), 
	"USERNAME" VARCHAR2(255), 
	"PASSWORD" VARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ANGGOTA
--------------------------------------------------------

  CREATE TABLE "PERPUSTAKAAN_BCHUB"."ANGGOTA" 
   (	"ANGGOTA_ID" VARCHAR2(10), 
	"NAMA" VARCHAR2(100), 
	"EMAIL" VARCHAR2(100), 
	"TELEPON" VARCHAR2(15), 
	"ALAMAT" VARCHAR2(255), 
	"PEKERJAAN" VARCHAR2(20), 
	 PRIMARY KEY ("ANGGOTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table BUKU
--------------------------------------------------------

  CREATE TABLE "PERPUSTAKAAN_BCHUB"."BUKU" 
   (	"BUKU_ID" VARCHAR2(20), 
	"JUDUL" VARCHAR2(255), 
	"PENULIS" VARCHAR2(100), 
	"PENERBIT" VARCHAR2(100), 
	"TAHUN_TERBIT" VARCHAR2(4), 
	"KATEGORI" VARCHAR2(20), 
	"SALINAN_TERSEDIA" VARCHAR2(20), 
	 PRIMARY KEY ("BUKU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PEMINJAMAN
--------------------------------------------------------

  CREATE TABLE "PERPUSTAKAAN_BCHUB"."PEMINJAMAN" 
   (	"ID_PEMINJAMAN" VARCHAR2(20), 
	"ANGGOTA_ID" VARCHAR2(10), 
	"BUKU_ID" VARCHAR2(20), 
	"TANGGAL_PEMINJAMAN" DATE, 
	"TANGGAL_PENGEMBALIAN" DATE, 
	 PRIMARY KEY ("ID_PEMINJAMAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ANGGOTA" FOREIGN KEY ("ANGGOTA_ID")
	  REFERENCES "PERPUSTAKAAN_BCHUB"."ANGGOTA" ("ANGGOTA_ID") ENABLE, 
	 CONSTRAINT "FK_BUKU" FOREIGN KEY ("BUKU_ID")
	  REFERENCES "PERPUSTAKAAN_BCHUB"."BUKU" ("BUKU_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ANGGOTA
--------------------------------------------------------

  CREATE TABLE "PERPUSTAKAAN_BCHUB"."ANGGOTA" 
   (	"ANGGOTA_ID" VARCHAR2(10), 
	"NAMA" VARCHAR2(100), 
	"EMAIL" VARCHAR2(100), 
	"TELEPON" VARCHAR2(15), 
	"ALAMAT" VARCHAR2(255), 
	"PEKERJAAN" VARCHAR2(20), 
	 PRIMARY KEY ("ANGGOTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table BUKU
--------------------------------------------------------

  CREATE TABLE "PERPUSTAKAAN_BCHUB"."BUKU" 
   (	"BUKU_ID" VARCHAR2(20), 
	"JUDUL" VARCHAR2(255), 
	"PENULIS" VARCHAR2(100), 
	"PENERBIT" VARCHAR2(100), 
	"TAHUN_TERBIT" VARCHAR2(4), 
	"KATEGORI" VARCHAR2(20), 
	"SALINAN_TERSEDIA" VARCHAR2(20), 
	 PRIMARY KEY ("BUKU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PEMINJAMAN
--------------------------------------------------------

  CREATE TABLE "PERPUSTAKAAN_BCHUB"."PEMINJAMAN" 
   (	"ID_PEMINJAMAN" VARCHAR2(20), 
	"ANGGOTA_ID" VARCHAR2(10), 
	"BUKU_ID" VARCHAR2(20), 
	"TANGGAL_PEMINJAMAN" DATE, 
	"TANGGAL_PENGEMBALIAN" DATE, 
	 PRIMARY KEY ("ID_PEMINJAMAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ANGGOTA" FOREIGN KEY ("ANGGOTA_ID")
	  REFERENCES "PERPUSTAKAAN_BCHUB"."ANGGOTA" ("ANGGOTA_ID") ENABLE, 
	 CONSTRAINT "FK_BUKU" FOREIGN KEY ("BUKU_ID")
	  REFERENCES "PERPUSTAKAAN_BCHUB"."BUKU" ("BUKU_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into PERPUSTAKAAN_BCHUB.ANGGOTA
SET DEFINE OFF;
Insert into PERPUSTAKAAN_BCHUB.ANGGOTA (ANGGOTA_ID,NAMA,EMAIL,TELEPON,ALAMAT,PEKERJAAN) values ('A0001','Doni','maulharun@gmail.com','0859106892004','Bandung	','Pelajar');
Insert into PERPUSTAKAAN_BCHUB.ANGGOTA (ANGGOTA_ID,NAMA,EMAIL,TELEPON,ALAMAT,PEKERJAAN) values ('A0002','Budi','budi@example.com','0897654678','Sapan','QWER');
Insert into PERPUSTAKAAN_BCHUB.ANGGOTA (ANGGOTA_ID,NAMA,EMAIL,TELEPON,ALAMAT,PEKERJAAN) values ('A0003','Lendra','lenulen@example.com','08591022121','Rakyat Cina','Coach');
Insert into PERPUSTAKAAN_BCHUB.ANGGOTA (ANGGOTA_ID,NAMA,EMAIL,TELEPON,ALAMAT,PEKERJAAN) values ('A0004','Restu F','restu@example.com','08122334412','Nagreg','Chunibiyo');
REM INSERTING into PERPUSTAKAAN_BCHUB.BUKU
SET DEFINE OFF;
Insert into PERPUSTAKAAN_BCHUB.BUKU (BUKU_ID,JUDUL,PENULIS,PENERBIT,TAHUN_TERBIT,KATEGORI,SALINAN_TERSEDIA) values ('B0001','Laut Bercerita','S.Laila Chudori','Gramedia','2020','Novel','1');
Insert into PERPUSTAKAAN_BCHUB.BUKU (BUKU_ID,JUDUL,PENULIS,PENERBIT,TAHUN_TERBIT,KATEGORI,SALINAN_TERSEDIA) values ('B0002','Pulang','Tere Liye','Republik','2021','Novel','2');
Insert into PERPUSTAKAAN_BCHUB.BUKU (BUKU_ID,JUDUL,PENULIS,PENERBIT,TAHUN_TERBIT,KATEGORI,SALINAN_TERSEDIA) values ('B0003','PL/SQL Menyenangkan','Dr. Djajeng','OuhHouse','2023','Akademik','3');
REM INSERTING into PERPUSTAKAAN_BCHUB.PEMINJAMAN
SET DEFINE OFF;
Insert into PERPUSTAKAAN_BCHUB.PEMINJAMAN (ID_PEMINJAMAN,ANGGOTA_ID,BUKU_ID,TANGGAL_PEMINJAMAN,TANGGAL_PENGEMBALIAN) values ('P0001','A0001','B0001',to_date('03-12-2024','DD-MM-RRRR'),to_date('09-12-2024','DD-MM-RRRR'));
Insert into PERPUSTAKAAN_BCHUB.PEMINJAMAN (ID_PEMINJAMAN,ANGGOTA_ID,BUKU_ID,TANGGAL_PEMINJAMAN,TANGGAL_PENGEMBALIAN) values ('P0002','A0001','B0001',to_date('15-12-2024','DD-MM-RRRR'),to_date('17-12-2024','DD-MM-RRRR'));
Insert into PERPUSTAKAAN_BCHUB.PEMINJAMAN (ID_PEMINJAMAN,ANGGOTA_ID,BUKU_ID,TANGGAL_PEMINJAMAN,TANGGAL_PENGEMBALIAN) values ('P0003','A0003','B0003',to_date('06-12-2024','DD-MM-RRRR'),to_date('17-12-2024','DD-MM-RRRR'));
REM INSERTING into PERPUSTAKAAN_BCHUB.ADMIN
SET DEFINE OFF;
Insert into PERPUSTAKAAN_BCHUB.ADMIN (ID_ADMIN,NAMA,USERNAME,PASSWORD) values ('1','admin','admin','123');
--------------------------------------------------------
--  DDL for Index SYS_C007014
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERPUSTAKAAN_BCHUB"."SYS_C007014" ON "PERPUSTAKAAN_BCHUB"."ANGGOTA" ("ANGGOTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERPUSTAKAAN_BCHUB"."SYS_C007015" ON "PERPUSTAKAAN_BCHUB"."BUKU" ("BUKU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007016
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERPUSTAKAAN_BCHUB"."SYS_C007016" ON "PERPUSTAKAAN_BCHUB"."PEMINJAMAN" ("ID_PEMINJAMAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007014
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERPUSTAKAAN_BCHUB"."SYS_C007014" ON "PERPUSTAKAAN_BCHUB"."ANGGOTA" ("ANGGOTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERPUSTAKAAN_BCHUB"."SYS_C007015" ON "PERPUSTAKAAN_BCHUB"."BUKU" ("BUKU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007016
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERPUSTAKAAN_BCHUB"."SYS_C007016" ON "PERPUSTAKAAN_BCHUB"."PEMINJAMAN" ("ID_PEMINJAMAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Procedure AMBIL_SEMUA_PEMINJAMAN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PERPUSTAKAAN_BCHUB"."AMBIL_SEMUA_PEMINJAMAN" (result_cursor OUT SYS_REFCURSOR) AS
BEGIN
    OPEN result_cursor FOR
        SELECT
            P.ID_PEMINJAMAN,
            P.ANGGOTA_ID,
            A.NAMA AS NAMA_ANGGOTA,
            P.BUKU_ID,
            B.JUDUL AS JUDUL_BUKU,
            P.TANGGAL_PEMINJAMAN,
            P.TANGGAL_PENGEMBALIAN
        FROM
            PEMINJAMAN P
        JOIN
            ANGGOTA A ON P.ANGGOTA_ID = A.ANGGOTA_ID
        JOIN
            BUKU B ON P.BUKU_ID = B.BUKU_ID;
END;
--------------------------------------------------------
--  DDL for Procedure DELETE_DATA_ANGGOTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PERPUSTAKAAN_BCHUB"."DELETE_DATA_ANGGOTA" (
p_anggota_id anggota.anggota_id%type)
AS
BEGIN
DELETE FROM anggota
WHERE anggota_id = p_anggota_id;
COMMIT;
END;
--------------------------------------------------------
--  DDL for Procedure DELETE_DATA_BUKU
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PERPUSTAKAAN_BCHUB"."DELETE_DATA_BUKU" (
p_buku_id buku.buku_id%type)
AS
BEGIN
DELETE FROM buku
WHERE buku_id = p_buku_id;
COMMIT;
END;
--------------------------------------------------------
--  DDL for Procedure INSERT_AND_DISPLAY_PEMINJAMAN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PERPUSTAKAAN_BCHUB"."INSERT_AND_DISPLAY_PEMINJAMAN" (
    p_id_peminjaman PEMINJAMAN.ID_PEMINJAMAN%TYPE,
    p_anggota_id PEMINJAMAN.ANGGOTA_ID%TYPE,
    p_buku_id PEMINJAMAN.BUKU_ID%TYPE,
    p_tanggal_peminjaman PEMINJAMAN.TANGGAL_PEMINJAMAN%TYPE,
    p_tanggal_pengembalian PEMINJAMAN.TANGGAL_PENGEMBALIAN%TYPE
) AS
BEGIN
    -- Memasukkan data ke dalam tabel PEMINJAMAN
    INSERT INTO PEMINJAMAN (ID_PEMINJAMAN, ANGGOTA_ID, BUKU_ID, TANGGAL_PEMINJAMAN, TANGGAL_PENGEMBALIAN)
    VALUES (p_id_peminjaman, p_anggota_id, p_buku_id, p_tanggal_peminjaman, p_tanggal_pengembalian);

    COMMIT; -- Menyimpan perubahan

    -- Menampilkan data peminjaman yang baru saja dimasukkan
    FOR rec IN (
        SELECT
            P.ID_PEMINJAMAN,
            A.NAMA AS NAMA_ANGGOTA,
            A.ANGGOTA_ID,
            B.JUDUL AS JUDUL_BUKU,
            B.BUKU_ID,
            P.TANGGAL_PEMINJAMAN,
            P.TANGGAL_PENGEMBALIAN
        FROM
            PEMINJAMAN P
        JOIN
            ANGGOTA A ON P.ANGGOTA_ID = A.ANGGOTA_ID
        JOIN
            BUKU B ON P.BUKU_ID = B.BUKU_ID
        WHERE
            P.ID_PEMINJAMAN = p_id_peminjaman
    ) LOOP
        -- Menampilkan hasil
        DBMS_OUTPUT.PUT_LINE('ID Peminjaman: ' || rec.ID_PEMINJAMAN ||
                             ', Anggota ID: ' || rec.ANGGOTA_ID ||
                             ', Nama Anggota: ' || rec.NAMA_ANGGOTA ||
                             ', Buku ID: ' || rec.BUKU_ID ||
                             ', Judul Buku: ' || rec.JUDUL_BUKU ||
                             ', Tanggal Peminjaman: ' || rec.TANGGAL_PEMINJAMAN ||
                             ', Tanggal Pengembalian: ' || rec.TANGGAL_PENGEMBALIAN);
    END LOOP;
END;
--------------------------------------------------------
--  DDL for Procedure INSERT_DATA_ANGGOTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PERPUSTAKAAN_BCHUB"."INSERT_DATA_ANGGOTA" (
  p_anggota_id anggota.anggota_id%type,
  p_nama anggota.nama%type,
  p_email anggota.email%type,
  p_telepon anggota.telepon%type,
  p_alamat anggota.alamat%type,
  p_pekerjaan anggota.pekerjaan%type
) AS
BEGIN
  INSERT INTO anggota (anggota_id, nama, email, telepon, alamat, pekerjaan)
  VALUES (p_anggota_id, p_nama, p_email, p_telepon, p_alamat, p_pekerjaan);

  -- Jika Anda ingin menyimpan perubahan, Anda bisa menggunakan COMMIT di sini
  -- COMMIT;
END;
--------------------------------------------------------
--  DDL for Procedure INSERT_DATA_BUKU
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PERPUSTAKAAN_BCHUB"."INSERT_DATA_BUKU" (
p_buku_id buku.buku_id%type,
p_judul buku.judul%type,
p_penulis buku.penulis%type,
p_penerbit buku.penerbit%type,
p_tahun_terbit buku.tahun_terbit%type,
p_kategori buku.kategori%type,
p_salinan_tersedia buku.salinan_tersedia%type
) AS
BEGIN
INSERT INTO buku (buku_id, judul, penulis, penerbit, tahun_terbit, kategori, salinan_tersedia)
VALUES (p_buku_id, p_judul, p_penulis, p_penerbit, p_tahun_terbit, p_kategori, p_salinan_tersedia);
COMMIT;
END;
--------------------------------------------------------
--  DDL for Procedure UPDATE_DATA_ANGGOTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PERPUSTAKAAN_BCHUB"."UPDATE_DATA_ANGGOTA" (
  p_anggota_id anggota.anggota_id%type,
  p_nama anggota.nama%type DEFAULT NULL,
  p_email anggota.email%type DEFAULT NULL,
  p_telepon anggota.telepon%type DEFAULT NULL,
  p_alamat anggota.alamat%type DEFAULT NULL,
  p_pekerjaan anggota.pekerjaan%type DEFAULT NULL
) AS
BEGIN
  UPDATE anggota
  SET
      nama = COALESCE(p_nama, nama),
      email = COALESCE(p_email, email),
      telepon = COALESCE(p_telepon, telepon),
      alamat = COALESCE(p_alamat, alamat),
      pekerjaan = COALESCE(p_pekerjaan, pekerjaan)
  WHERE anggota_id = p_anggota_id;

  COMMIT;
END;
--------------------------------------------------------
--  DDL for Procedure UPDATE_DATA_BUKU
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PERPUSTAKAAN_BCHUB"."UPDATE_DATA_BUKU" (
p_buku_id buku.buku_id%type,
p_judul buku.judul%type,
p_penulis buku.penulis%type,
p_penerbit buku.penerbit%type,
p_tahun_terbit buku.tahun_terbit%type,
p_kategori buku.kategori%type,
p_salinan_tersedia buku.salinan_tersedia%type
) AS
BEGIN
UPDATE buku
SET
judul = COALESCE(p_judul, judul),
penulis = COALESCE(p_penulis, penulis),
penerbit = COALESCE(p_penerbit, penerbit),
tahun_terbit = COALESCE(p_tahun_terbit, tahun_terbit),
kategori = COALESCE(p_kategori, kategori),
salinan_tersedia = COALESCE(p_salinan_tersedia, salinan_tersedia)
WHERE buku_id = p_buku_id;
COMMIT;
END;
--------------------------------------------------------
--  DDL for Synonymn DBMS_OUTPUT
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DBMS_OUTPUT" FOR "SYS"."DBMS_OUTPUT"
--------------------------------------------------------
--  Constraints for Table ANGGOTA
--------------------------------------------------------

  ALTER TABLE "PERPUSTAKAAN_BCHUB"."ANGGOTA" ADD PRIMARY KEY ("ANGGOTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table BUKU
--------------------------------------------------------

  ALTER TABLE "PERPUSTAKAAN_BCHUB"."BUKU" ADD PRIMARY KEY ("BUKU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table PEMINJAMAN
--------------------------------------------------------

  ALTER TABLE "PERPUSTAKAAN_BCHUB"."PEMINJAMAN" ADD PRIMARY KEY ("ID_PEMINJAMAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table PEMINJAMAN
--------------------------------------------------------

  ALTER TABLE "PERPUSTAKAAN_BCHUB"."PEMINJAMAN" ADD CONSTRAINT "FK_ANGGOTA" FOREIGN KEY ("ANGGOTA_ID")
	  REFERENCES "PERPUSTAKAAN_BCHUB"."ANGGOTA" ("ANGGOTA_ID") ENABLE
  ALTER TABLE "PERPUSTAKAAN_BCHUB"."PEMINJAMAN" ADD CONSTRAINT "FK_BUKU" FOREIGN KEY ("BUKU_ID")
	  REFERENCES "PERPUSTAKAAN_BCHUB"."BUKU" ("BUKU_ID") ENABLE
